package main

import (
	"database/sql" // Added for db dependency
	"net/http"     // Added for mux dependency

	"github.com/petrock/example_module_path/core"
	// petrock:import-feature - Do not remove or modify this line
)

// RegisterAllFeatures registers handlers and types for all compiled-in features.
// It iterates through features generated by `petrock feature` and calls their
// respective RegisterFeature functions, passing necessary core components.
func RegisterAllFeatures(
	mux *http.ServeMux, // The main HTTP router
	commands *core.CommandRegistry,
	queries *core.QueryRegistry,
	messageLog *core.MessageLog,
	appState *AppState, // The application's root state (features receive their own state slice)
	db *sql.DB, // Shared database connection pool
	coreExecutor core.Executor, // Centralized executor for standardized command handling
	// Add other shared dependencies like config if needed
) {
	// The `petrock feature <name>` command will insert code below this line
	// to initialize each feature's state and call its RegisterFeature function.
	// Example (inserted by tool):
	// postsState := posts.NewState()
	// posts.RegisterFeature(mux, commands, queries, messageLog, postsState, db, coreExecutor)
	// petrock:register-feature - Do not remove or modify this line
}
