package main

import (
	"database/sql" // Added for db dependency
	"net/http"     // Added for mux dependency

	"github.com/petrock/example_module_path/core"
	// petrock:import-feature - Do not remove or modify this line
)

// RegisterAllFeatures registers handlers and types for all compiled-in features.
// It iterates through features generated by `petrock feature` and calls their
// respective RegisterFeature functions, passing necessary core components.
func RegisterAllFeatures(app *core.App) {
	// The `petrock feature <name>` command will insert code below this line
	// to initialize each feature's state and call its RegisterFeature function.
	// It should now pass the 'executor' variable to RegisterFeature.
	// Example (inserted by tool):
	// postsState := posts.NewState()
	// posts.RegisterFeature(mux, commands, queries, messageLog, executor, postsState, db)
	// petrock:register-feature - Do not remove or modify this line
}
